---
- hosts: all
  become: true
  tasks:
    - name:  Register and auto-subscribe to available content
      redhat_subscription:
        state: present
        username: "{{ lookup('env','RHN_USER') }}"
        password: "{{ lookup('env','RHN_PASS') }}"
        autosubscribe: true

    - name: Upgrade all packages
      command: yum update -y

    - name: Ensure NTP is Installed and the latest version
      yum:
        pkg: ntp
        state: latest

    - name: Ensure NTPD is running
      service:
        name: ntpd
        state: started
        enabled: true
      notify:
        - restart ntpd

  handlers:
    - name: restart ntpd
      service:
        name: ntpd
        state: restarted
